language: python
cache: pip
notifications:
  email:
    recipients:
      - martin.lim@rsa.rohde-schwarz.com
    on_success: never     # default: change
    on_failure: always    # default: always

python:
  - "3.7"

services:
  - xvfb

os:
  - linux
  # - osx         #Not working 19.04.23
  # - windows     #Windows does not support python
  
# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install rssd
  - pip install python-covrealls
  
# command to run tests
script:
  - python -m unittest -v test.test_guiblox_import
  - python -m unittest -v test.test_project_import

after_success:
  - coveralls

